name: run-tests

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        php: [8.4]
        laravel: [12.*]

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: "Installing php"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring, xdebug
          coverage: xdebug
          tools: composer

      - name: Show PHP version
        run: php -v && composer -V

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction

      - name: Run tests
        run: |
          ./vendor/bin/pest --parallel --coverage-clover coverage.xml

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
